name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: vue3-ci
  NOW: $GITHUB_RUN_ID

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install --legacy-peer-deps --no-audit --silent
    - run: npm run lint
    - run: npm run build

    - name: build dist cache
      id: build-dist-cache
      uses: actions/cache@v3
      with:
        path: dist
        key: ${{ runner.os }}-dist

  build-image:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:

    # - name: Set current date as env variable
    #   run: echo "NOW=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
    # - name: Echo current date
    #   run: echo $NOW

    - uses: actions/checkout@v3

    - name: build dist cache
      id: build-dist-cache
      uses: actions/cache@v3
      with:
        path: dist
        key: ${{ runner.os }}-dist

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.NOW }}

    - name: image cache
      id: image-cache
      uses: actions/cache@v3
      with:
        path: ${{ env.IMAGE_NAME }}:${{ env.NOW }}
        key: ${{ runner.os }}-image

  push-image-docker:
    needs: ['build-image']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: image cache
        id: image-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.IMAGE_NAME }}:${{ env.NOW }}
          key: ${{ runner.os }}-image

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: abcprintf/vue3-ci:latest, abcprintf/vue3-ci:${{ github.run_number }}
          cache-from: type=local,src=${{ env.IMAGE_NAME }}:${{ env.NOW }}
          cache-to: type=local,dest=${{ env.IMAGE_NAME }}:${{ env.NOW }}-image,mode=max